# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "worker"
main = "./.output/server/index.mjs"
compatibility_date = "2024-05-07"

[[d1_databases]]
binding = "DB"
database_name = "default"
database_id = "db46ae3b-5d96-44a6-b431-274dba530949"
migrations_dir = "./server/database/migrations"